-- MySQL Script generated by MySQL Workbench
-- Qui 08 Jun 2017 10:39:44 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema infomedicine
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema infomedicine
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `infomedicine` CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `infomedicine` ;

-- -----------------------------------------------------
-- Table `infomedicine`.`Fabricante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infomedicine`.`Fabricante` (
  `Nome` VARCHAR(100) NOT NULL,
  `Imagem_URL` VARCHAR(200) NULL,
  `Descricao` TEXT NULL,
  `Contato` TINYTEXT NULL,
  `Endereco` TINYTEXT NULL,
  PRIMARY KEY (`Nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infomedicine`.`Principio_Ativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infomedicine`.`Principio_Ativo` (
  `Nome` VARCHAR(100) NOT NULL,
  `Descricao` TEXT NULL,
  PRIMARY KEY (`Nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infomedicine`.`Medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infomedicine`.`Medicamento` (
  `Nome` VARCHAR(100) NOT NULL,
  `Imagem_URL` VARCHAR(45) NULL,
  `Codigo_de_Registro` VARCHAR(45) NULL,
  `Referencia` VARCHAR(100) NULL,
  `Apresentacao` TEXT NULL,
  `Precaucoes` TEXT NULL,
  `Esquemas_de_Administracao` TEXT NULL,
  `Aspectos_Framacologico_Clinicamente_Relevantes` TEXT NULL,
  `Efeitos_Adversos` TEXT NULL,
  `Interacoe_Medicamentosas` TEXT NULL,
  `Orientacoes_aos_Pacientes` TEXT NULL,
  `Aspectos_Farmaceuticos` TEXT NULL,
  `Advertencias` TEXT NULL,
  `Fabricante` VARCHAR(100) NOT NULL,
  `Principio_Ativo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Nome`, `Fabricante`, `Principio_Ativo`),
  INDEX `fk_Medicamento_Fabricante_idx` (`Fabricante` ASC),
  INDEX `fk_Medicamento_Principio_Ativo1_idx` (`Principio_Ativo` ASC),
  CONSTRAINT `fk_Medicamento_Fabricante`
    FOREIGN KEY (`Fabricante`)
    REFERENCES `infomedicine`.`Fabricante` (`Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medicamento_Principio_Ativo1`
    FOREIGN KEY (`Principio_Ativo`)
    REFERENCES `infomedicine`.`Principio_Ativo` (`Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
