-- MySQL Script generated by MySQL Workbench
-- 06/03/17 08:44:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema infomedicine
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema infomedicine
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `infomedicine` DEFAULT CHARACTER SET utf8 ;
USE `infomedicine` ;

-- -----------------------------------------------------
-- Table `infomedicine`.`principioativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infomedicine`.`principioativo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TEXT NOT NULL,
  `imagem` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infomedicine`.`fabricante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infomedicine`.`fabricante` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TEXT NOT NULL,
  `imagem` VARCHAR(100) NULL,
  `contato` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infomedicine`.`medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infomedicine`.`medicamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `descricao` TEXT NOT NULL,
  `imagem` VARCHAR(100) NULL,
  `fabricante` INT NOT NULL,
  `codigodebarras` VARCHAR(13) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_medicamento_fabricante1_idx` (`fabricante` ASC),
  CONSTRAINT `fk_medicamento_fabricante1`
    FOREIGN KEY (`fabricante`)
    REFERENCES `infomedicine`.`fabricante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infomedicine`.`contraindicacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infomedicine`.`contraindicacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  `imagem` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infomedicine`.`principioativo_has_medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infomedicine`.`principioativo_has_medicamento` (
  `principioativo` INT NOT NULL,
  `medicamento` INT NOT NULL,
  PRIMARY KEY (`principioativo`, `medicamento`),
  INDEX `fk_principioativo_has_medicamento_medicamento1_idx` (`medicamento` ASC),
  INDEX `fk_principioativo_has_medicamento_principioativo1_idx` (`principioativo` ASC),
  CONSTRAINT `fk_principioativo_has_medicamento_principioativo1`
    FOREIGN KEY (`principioativo`)
    REFERENCES `infomedicine`.`principioativo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_principioativo_has_medicamento_medicamento1`
    FOREIGN KEY (`medicamento`)
    REFERENCES `infomedicine`.`medicamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infomedicine`.`principioativo_has_contraindicacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infomedicine`.`principioativo_has_contraindicacao` (
  `principioativo` INT NOT NULL,
  `contraindicacao` INT NOT NULL,
  PRIMARY KEY (`principioativo`, `contraindicacao`),
  INDEX `fk_principioativo_has_contraindicacao_contraindicacao1_idx` (`contraindicacao` ASC),
  INDEX `fk_principioativo_has_contraindicacao_principioativo1_idx` (`principioativo` ASC),
  CONSTRAINT `fk_principioativo_has_contraindicacao_principioativo1`
    FOREIGN KEY (`principioativo`)
    REFERENCES `infomedicine`.`principioativo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_principioativo_has_contraindicacao_contraindicacao1`
    FOREIGN KEY (`contraindicacao`)
    REFERENCES `infomedicine`.`contraindicacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
